receivers:
  hostmetrics:
    collection_interval: 5s
    scrapers:
      memory:
      network:
      cpu:
      disk:

      # process:
      # not currently supported on macOS:
      #   metrics:
      #     process.memory.physical_usage:
      #       enabled: false
      #     process.memory.virtual_usage:
      #       enabled: false
      #     process.memory.usage:
      #       enabled: true
      #     process.memory.virtual:
      #       enabled: true

  hostmetrics/disk:
    root_path: /
    collection_interval: 30s
    scrapers:
      filesystem:
        include_mount_points:
          match_type: strict
          mount_points:
            - /

  # otlp:
  #   protocols:
  #     grpc:
  #     http:

processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 30
  attributes/example:
    actions:
      - key: vm.job.id
        value: qux-yuiy3-3y8793
        action: upsert

exporters:

  otlp:
    endpoint: 127.0.0.1:4317
    auth:
      authenticator: basicauth/client
    tls:
      insecure: false
      insecure_skip_verify: true

extensions:
  zpages: # https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/zpagesextension/README.md

  # memory_ballast: # reduces GC - see https://blog.twitch.tv/en/2019/04/10/go-memory-ballast-how-i-learnt-to-stop-worrying-and-love-the-heap/
  #   size_mib: 64

  basicauth/client:
    client_auth: 
      username: username
      password: password

service:
  extensions: [zpages, basicauth/client]
  telemetry:
    metrics:
      # address: 0.0.0.0:8888
      level: none
  pipelines:
    metrics:
      receivers: [hostmetrics, hostmetrics/disk]
      processors: [batch, memory_limiter, attributes/example]
      exporters: [otlp]
