receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        tls:
          cert_file: /server.crt
          key_file: /server.key
          # insecure: true
        auth:
          authenticator: basicauth/server
      http:
        endpoint: 0.0.0.0:4318
        auth:
          authenticator: basicauth/server

processors:
  batch:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 50
    spike_limit_percentage: 30

exporters:

  prometheus:
    endpoint: 0.0.0.0:9000
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
    resource_to_telemetry_conversion:
      enabled: true

  # prometheusremotewrite:
  #   endpoint: "http://some.url:9411/api/prom/push"

extensions:
  zpages: # https://github.com/open-telemetry/opentelemetry-collector/blob/main/extension/zpagesextension/README.md

  # memory_ballast: # reduces GC - see https://blog.twitch.tv/en/2019/04/10/go-memory-ballast-how-i-learnt-to-stop-worrying-and-love-the-heap/
  #   size_mib: 64

  basicauth/server:
    htpasswd: 
      # file: .htpasswd
      inline: |
        username:password

service:
  extensions: [zpages, basicauth/server]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch, memory_limiter]
      exporters: [prometheus]
